POST /account-api/account HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "id": "exampleID3",
  "password": "securePassword3",
  "email": "example3@email.com",
  "name": "Example Name3"
}

### GET id
GET /account-api/accounts/id/exampleID HTTP/1.1
Host: localhost:8080
Content-Type: application/json

### GET email
GET /account-api/accounts/email/example@email.com HTTP/1.1
Host: localhost:8080
Content-Type: application/json

### CREATE STATUS BY ID
POST /account-api/create/status/id HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "idOrEmail": "exampleID",
  "accountStateCode": "03"
}

### CREATE STATUS BY EMAIL
POST /account-api/create/status/email HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "idOrEmail": "example@email.com",
  "accountStateCode": "03"
}
### LOGIN
GET /account-api/login/exampleID/state HTTP/1.1
Host: localhost:8080

### UPDATE NAME BY ID
PUT /account-api/update/name/id HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "idOrEmail": "exampleID",
  "name": "UpdatedById Name"
}

### UPDATE NAME BY EMAIL
PUT /account-api/update/name/email HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "idOrEmail": "example@email.com",
  "name": "UpdatedByEmail Name"
}

### UPDATE PASSWORD BY ID
PUT /account-api/update/password/id HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "idOrEmail": "exampleID",
  "password": "updatedByIdPassword"
}

### UPDATE PASSWORD BY EMAIL
PUT /account-api/update/password/email HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "idOrEmail": "example@email.com",
  "password": "updatedByEmailPassword"
}

### GET ACCOUNTS
GET /account-api/accounts HTTP/1.1
Host: localhost:8080
Content-Type: application/json

### DEACT ACCOUNT BY ID
GET /account-api/deact/id/exampleId/state HTTP/1.1
Host: localhost:8080

### DEACT ACCOUNT BY EMAIL
GET /account-api/deact/email/example@email.com/state HTTP/1.1
Host: localhost:8080

### DEACT ACCOUNT ALL
GET /account-api/deact/all/state HTTP/1.1
Host: localhost:8080