POST /account-api/account HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "id": "exampleID",
  "password": "securePassword",
  "email": "example@email.com",
  "name": "Example Name"
}

### GET id
GET /account-api/exampaleID HTTP/1.1
Host: localhost:8080
Content-Type: application/json

### GET email
GET /account-api/email/example@email.com HTTP/1.1
Host: localhost:8080
Content-Type: application/json

### CREATE status
POST /account-api/status HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "accountId": "exampleID",
  "accountStateCode": "03"
}

### LOGIN
GET /account-api/login/exampleID HTTP/1.1
Host: localhost:8080